peassignment/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth.decorators import login_required

from core.forms import LoginForm
from core.views import home, PrescriptionDetailView, MedicalRecordDetailView, patient_approve, approval_create
from django.contrib.auth import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home, name='home'),
    url(r'^login/$', views.login, {'template_name': 'login.html', 'authentication_form': LoginForm}, name='login'),
    url(r'^logout/$', views.logout, {'next_page': '/login'}, name='logout'),
    url(r'^prescription/(?P<pk>[0-9]+)/$', login_required(PrescriptionDetailView.as_view()), name='prescription-detail'),
    url(r'^medicalrecord/(?P<pk>[0-9]+)/$', login_required(MedicalRecordDetailView.as_view()), name='medicalrecord-detail'),
    url(r'^approval/(?P<pk>[0-9]+)/$', patient_approve, name='patient_approve'),
    url(r'^approval/$', approval_create, name='approval_create'),
]

core/models.py
from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.core.mail import send_mail
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField

__author__ = 'vatsalshah'


class UserManager(BaseUserManager):
    def create_user(self, email, name, phone, user_type, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            name=name,
            phone=phone,
            user_type=user_type
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, name, phone, password):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(email,
                                password=password,
                                name=name,
                                phone=phone,
                                user_type='NA'
                                )
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    """
    Custom User model
    """
    created_at = models.DateTimeField(
        verbose_name='created at',
        auto_now_add=True
    )
    updated_at = models.DateTimeField(
        verbose_name='updated at',
        auto_now=True
    )
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True
    )
    name = models.CharField(
        verbose_name='full name',
        max_length=255
    )
    USER_TYPES = (
        ('PA', 'Patient'),
        ('DO', 'Doctor'),
        ('PH', 'Pharmacist'),
        ('NA', 'Not Applicable')
    )
    user_type = models.CharField(
        verbose_name='user type',
        max_length=2,
        default='PA',
        choices=USER_TYPES
    )
    phone = PhoneNumberField()

    is_staff = models.BooleanField(
        default=False,
        help_text='Designates whether the user can log into this admin site.'
    )
    is_active = models.BooleanField(
        default=True,
        help_text='Designates whether this user should be treated as active.'
    )

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name', 'phone']

    class Meta:
        ordering = ["created_at"]
        verbose_name = 'User'

    def get_full_name(self):
        """
        Returns the first_name plus the last_name, with a space in between.
        """
        return self.name

    def get_short_name(self):
        """
        Returns the short name for the user.
        """
        return self.name.split(' ')[0]

    def email_user(self, subject, message, from_email=None, **kwargs):
        """
        Sends an email to this User.
        """
        send_mail(subject, message, from_email, [self.email], **kwargs)

    def __str__(self):
        return self.email


class MedicalRecord(models.Model):
    """
    User Medical Records
    """
    created_at = models.DateTimeField(
        auto_now_add=True
    )
    updated_at = models.DateTimeField(
        auto_now=True
    )
    user = models.ForeignKey(
        to=User,
        related_name='medicalrecord_user'
    )
    doctor = models.ForeignKey(
        to=User,
        related_name='medicalrecord_doctor'
    )
    diagnosis = models.TextField(blank=True)

    def __str__(self):
        return "Doctor: {}, User: {}, Diagnosis: {}".format(self.doctor.name, self.user.name, self.diagnosis)

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('medicalrecord-detail', args=[str(self.id)])


class Prescription(models.Model):
    """
    Medicine Prescription
    """
    created_at = models.DateTimeField(
        auto_now_add=True
    )
    updated_at = models.DateTimeField(
        auto_now=True
    )
    user = models.ForeignKey(
        to=User,
        related_name='prescription_user'
    )
    doctor = models.ForeignKey(
        to=User,
        related_name='prescription_doctor'
    )
    medical_record = models.ForeignKey(
        to=MedicalRecord,
        blank=True,
        null=True
    )

    def __str__(self):
        return self.user.email

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('prescription-detail', args=[str(self.id)])


class Medicine(models.Model):
    """
    Medicine
    """
    created_at = models.DateTimeField(
        auto_now_add=True
    )
    updated_at = models.DateTimeField(
        auto_now=True
    )
    name = models.CharField(max_length=100)
    qty = models.IntegerField()
    strength = models.IntegerField()
    frequency = models.CharField(max_length=50)
    prescription = models.ForeignKey(
        to=Prescription
    )

    def __str__(self):
        return self.name


class Approval(models.Model):
    """
    Approvals
    """
    created_at = models.DateTimeField(
        auto_now_add=True
    )
    updated_at = models.DateTimeField(
        auto_now=True
    )
    prescription = models.ForeignKey(
        to=Prescription
    )
    user = models.ForeignKey(
        to=User
    )
    STATUS_TYPES = (
        ('PE', 'Pending'),
        ('RE', 'Rejected'),
        ('AP', 'Approved')
    )
    status = models.CharField(
        max_length=2,
        default='PE',
        choices=STATUS_TYPES
    )

    def __str__(self):
        return self.user.email

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>PharmEasy Assignment</title>
                <!-- Core CSS - Include with every page -->
                <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
                </head>
                <body>
                    <nav class="navbar navbar-default">
                        <div class="container-fluid">
                            <div class="navbar-header">
                                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                                    <span class="sr-only">Toggle navigation</span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>
                                <a class="navbar-brand" href="/">PharmEasy Assignment - Dashboard</a>
                            </div>
                            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                                <ul class="nav navbar-nav navbar-right">
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Account
                                            <span class="caret"></span>
                                        </a>
                                        <ul class="dropdown-menu" role="menu">
                                            <li>
                                                <a href="/">Home</a>
                                            </li>
                                            <li class="divider"></li>
                                            <li>
                                                <a href="/logout">Logout</a>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </nav>

                {% block content %}
                {% endblock %}


                    <!-- Core Scripts - Include with every page -->
                    <script   src="https://code.jquery.com/jquery-3.2.1.min.js"   integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="   crossorigin="anonymous"></script>
                    <script src = "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        {% block javascript %}
        {% endblock %}


            </body>
        </html>

templates/index.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="jumbotron">
            {% if user.user_type == "PA" %}
                <h2>Your Prescriptions</h2>
                <ul>
                {% for prescription in user.prescription_user.all %}
                    <li><a href="{{ prescription.get_absolute_url }}">Patient name: {{ prescription.user.name }}, Doctor: {{ prescription.doctor.name }}, Date: {{ prescription.created_at|date:"SHORT_DATE_FORMAT" }}</a></li>
                {% empty %}
                    <li>Sorry, no prescriptions available.</li>
                {% endfor %}
                </ul>
                <span></span>
                <h2>Pending Approvals</h2>
                <ul>
                {% for approval in pending_approvals %}
                    <li>User type: {{ approval.user.get_user_type_display }}, User name: {{ approval.user.name }}, Prescription Date: {{ approval.prescription.created_at|date:"SHORT_DATE_FORMAT" }} <button type="submit"><a href="{% url 'patient_approve' approval.id %}">Approve</a></button></li>
                {% empty %}
                    <li>Sorry, no prescriptions available.</li>
                {% endfor %}
                </ul>
            {% else %}
                <h2>Approved Patient Prescriptions</h2>
                <ul>
                {% for prescription in approved_prescriptions %}
                    <li><a href="{{ prescription.get_absolute_url }}">Patient name: {{ prescription.user.name }}, Doctor: {{ prescription.doctor.name }}, Date: {{ prescription.created_at|date:"SHORT_DATE_FORMAT" }}</a></li>
                {% empty %}
                    <li>Sorry, no prescriptions available.</li>
                {% endfor %}
                <span></span>
                <h2>Pending Patient Approval Prescriptions</h2>
                <ul>
                {% for prescription in pending_prescriptions %}
                    <li>Patient name: {{ prescription.user.name }}, Doctor: {{ prescription.doctor.name }}, Date: {{ prescription.created_at|date:"SHORT_DATE_FORMAT" }}</li>
                {% empty %}
                    <li>Sorry, no prescriptions available.</li>
                {% endfor %}
                </ul>
                <span></span>
                <h2>Available Prescriptions - Needs Approval</h2>
                <ul>
                {% for prescription in available_prescriptions %}
                    <li>Patient name: {{ prescription.user.name }}, Doctor: {{ prescription.doctor.name }}, Date: {{ prescription.created_at|date:"SHORT_DATE_FORMAT" }}</li>
                    <form action="{% url 'approval_create' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="user" value="{{ user.pk }}">
                    <input type="hidden" name="prescription" value="{{ prescription.pk }}">
                    <input type="submit" value="Ask for approval">
                    </form>
                {% empty %}
                    <li>Sorry, no prescriptions available.</li>
                {% endfor %}
                </ul>
                <span></span>
                <h2>Rejected Patient Approval Prescriptions</h2>
                <ul>
                {% for prescription in rejected_prescriptions %}
                    <li>Patient name: {{ prescription.user.name }}, Doctor: {{ prescription.doctor.name }}, Date: {{ prescription.created_at|date:"SHORT_DATE_FORMAT" }}</li>
                {% empty %}
                    <li>Sorry, no prescriptions available.</li>
                {% endfor %}
                </ul>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}


{% block content %}
    {% if form.errors %}

<p>Your email and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}

<p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}

<p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="login-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Please Sign In</h3>
                </div>
                <div class="panel-body">
                    <form method="post" action="{% url 'login' %}">
{% csrf_token %}

                        <p class="bs-component">
                            <table>
                                <tr>
                                    <td>{{ form.username.label_tag }}</td>
                                    <td>{{ form.username }}</td>
                                </tr>
                                <tr>
                                    <td>{{ form.password.label_tag }}</td>
                                    <td>{{ form.password }}</td>
                                </tr>
                            </table>
                        </p>
                        <p class="bs-component">
                            <center>
                                <input class="btn btn-success btn-sm" type="submit" value="login" />
                            </center>
                        </p>
                        <input type="hidden" name="next" value="{{ next }}" />
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block javascript %}


<script>
{% if not user.is_authenticated %}
$("ul.nav.navbar-nav.navbar-right").css("display","none");
{% endif %}
</script>

{% endblock %}

templates/medicalrecord_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="jumbotron">
            <p>Patient name: {{ object.user.name }}</p>
            <p>Doctor name: {{ object.doctor.name }}</p>
            <p>Diagnosis: {{ object.diagnosis }}</p>
            <p>Date: {{ object.created_at|date:"SHORT_DATE_FORMAT" }}</p>
        </div>
    </div>
</div>
{% endblock %}

templates/prescription_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="jumbotron">
            <p>Patient name: {{ object.user.name }}</p>
            <p>Doctor name: {{ object.doctor.name }}</p>
            <p>Date: {{ object.created_at|date:"SHORT_DATE_FORMAT" }}</p>
            {% if  object.medical_record %}
            <a href="{{ object.medical_record.get_absolute_url }}">Medical Record</a>
            {% endif %}
            <span></span>

            {% for medicine in object.medicine_set.all %}
                <ul class="list-unstyled">
                <li>Name: {{ medicine.name }}</li>
                <li>Qty: {{ medicine.qty }}</li>
                <li>Strength: {{ medicine.strength }}</li>
                <li>Frequency: {{ medicine.frequency }}</li>
                <li></li>
                </ul>
            {% empty %}
                <ul class="list-unstyled">
                <li>Sorry, no medicines prescribed.</li>
                </ul>
            {% endfor %}

        </div>
    </div>
</div>
{% endblock %}